---
# file: tasks/controller.yml
- name: Prepare controller
  npm: name=cozy-controller global=yes

- name: Create directories
  file: path=/etc/cozy/pids state=directory

- name: Configure Cozy controller
  template: src=controller.token.j2 dest=/etc/cozy/controller.token owner=cozy-home mode=0700

- name: Copy Supervisor file for Cozy controller
  copy: src=cozy-controller.conf dest=/etc/supervisor/conf.d/cozy-controller.conf owner=root mode=0755
  notify: Restart Cozy controller

- include: supervisor_restart.yml tags=restart-supervisor

- wait_for: host=127.0.0.1 port=9002 delay=10 state=drained

- name: Check Cozy's components status
  shell: cozy-monitor status > /tmp/status
  ignore_errors: True

- name: Check if cozy-controller is properly running
  shell: cat /tmp/status | grep controller | grep up && rm -f /tmp/status
