---
# file: tasks/nginx.yml

 - name: create self-signed SSL cert
   command: openssl req -new -nodes -x509 -subj "/CN=${ansible_fqdn}" -days 3650 -keyout /etc/cozy/server.key -out /etc/cozy/server.crt -extensions v3_ca creates=/etc/cozy/server.crt

 - name: create a DH parameter
   command: openssl dhparam -out /etc/cozy/dhparam.pem 2048

 - name: Install nginx config
   template: src=nginx.conf.j2 dest=/etc/nginx/conf.d/cozy.conf owner=root mode=644
   notify: Restart nginx
